encoding: utf-8
plugins:
  - jekyll-feed
  - jekyll-sitemap
permalink: /blog/:title
collections:
  lists:
    output: true
comments:
  provider: disqus
disqus:
  shortname: for-all-k
github: [metadata]
defaults:
  -
    scope:
      path: ""
      type: posts
    values:
      layout: post
      comments: true
